services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229  
    command: pnpm run start:dev  
    env_file:
      - .env 
    networks:
      - webnet

networks:
  webnet:

volumes:
  pgdata:
